### ISSUE TITLE
Assign IP Address to Guests

### ISSUE THREAD

**Issue by meekjt** [pr1ntf/iohyve#100]
Newbie here, is it possible to assign an IP address to a guest similar to the iocage command below?

```
iocage set ip4_addr="em0|10.1.1.10/24" UUID| TAG
```

Or, should I manage the IP address within the guest?

Thanks for the awesome utility!

**Comment by pr1ntf** [comment]
Thanks for the kind words! :grin: 

There is currently no way to set an IP in a guest (kind of by design).

Think of a guest as it's own computer, with it's own kernel. In order to change the IP address on a physical computer, you either need to log in physically to it or have some sort of software "baked into" the OS like SaltStack or any number of those fancy pants DevOps tools.
