### ISSUE TITLE
loader=uefi start failed

### ISSUE THREAD

**Issue by SquallATF** [pr1ntf/iohyve#117]
I created a vm run ubuntu 14.04.4 with uefi named UEFI
vm can run with `iohyve uefi UEFI null.iso` but failed with `iohyve start UEFI`

> iohyve start UEFI
> grep: tap3: No such file or directory
> grep: tap3: No such file or directory
> grep: tap2: No such file or directory
> grep: tap2: No such file or directory
> grep: tap0: No such file or directory
> grep: tap0: No such file or directory
> grep: tap1: No such file or directory
> grep: tap1: No such file or directory
> grep: tap1: No such file or directory
> ifconfig: interface - does not exist
> ifconfig: BRDGADD -: No such file or directory
> [: -: unexpected operator
> You must enter at least a zero byte ISO for some OSs...
> EX: iohyve uefi winguest null.iso
> Not a valid guest name
> Starting UEFI... (Takes 15 seconds for FreeBSD guests)

all profile

> iohyve getall UEFI
> Getting UEFI props...
> persist      1
> boot         0
> install      no
> description  Mon
> name         UEFI
> tap          tap3
> bargs        -A_-H_-P
> con          nmdm4
> autogrub     \n
> os           debian
> ram          256M
> cpu          1
> fw           BHYVE_UEFI_20151002.fd
> loader       uefi
> size         5G

**Comment by pr1ntf** [comment]
This is expected. Because `iohyve` handles the guest preparation differently when using `UEFI`, using the `start` function will not work properly.  There was some work done in `iohyve` to fix this, but it has since broken and needs some love. 

Please note that `UEFI` support is experimental at this time in `iohyve`. There are future plans to fix this, probably after the `GRUB` support gets fixed. You can see more on that in the [Roadmap](https://github.com/pr1ntf/iohyve/wiki/General-Path-to-1.0#079-goals) in the Wiki.
