### ISSUE TITLE
iohyve setup issues/questions

### ISSUE THREAD

**Issue by till** [pr1ntf/iohyve#118]
1. I was trying to run setup (`iohyve setup tank=zroot`) and it created a zfs dataset but it mounted it into `/iohyve/zroot` which seems to make `fetch` work, but subsequent calls fail. There's also a weird error/warning during: `cannot create 'zroot/iohyve/ISO/FreeBSD-10.1-RELEASE-amd64-bootonly.iso': parent does not exist` (and then it seems to complete, but `isolist` doesn't find anything. For the record, the same command works when I use the port so it must have been fixed.
2. More a general question, do you happen to know why `pkg install iohyve` gets `0.7` and the port is up to date?
3. Generally, I am not a real pro at bash, but I tried to read through the script e.g. to find out what "setup" does exactly, would you be open for a PR with some documentation? And if so, what format do you prefer?
4. LBNL, ever consider something a little more high-level than bash? Kind of curious what your thoughts are.

**Comment by pr1ntf** [comment]
1. The syntax is `iohyve setup pool=poolname` as stated in the [Readme](https://github.com/pr1ntf/iohyve/blob/master/README.md) and the [man page](https://github.com/pr1ntf/iohyve/blob/master/iohyve.8.txt#L62). The issue you are seeing is because you have already set up `zroot` as your primary zpool to store iohyve datasets in. This is a bug in the multiple pool support. I have opened an issue regarding this, #122
2. No idea how that works. You may want to ping the maintainer, lme@, about that. He takes care of the actual commit to ports. 
3. (It's not `bash`, FreeBSD does not come with the Bourne Again Shell installed, instead we take advantage of `/bin/sh`) What issues are you having? I'd be happy to go over it with you. `pool=poolname` tells iohyve to make iohyve datasets on that pool, used only once. `kmod=[0|1]` loads the proper kernel modules required to run `bhyve` (`vmm`) and the nullmodem support (`nmdm`) for serial consoles. `net=[interface]` does the network setup so you don't have to edit your `/etc/rc.conf` network settings; it basically attaches the interface to `bridge0` and tells iohyve to attach all taps to that bridge. `kmod` and `net` must be run everytime after you reboot, so I included a part of the `rc.d` script that allows you to add `iohyve_flags="kmod=1 net=em0"` to your `/etc/rc.conf` file. This is also in the [Readme](https://github.com/pr1ntf/iohyve/blob/master/README.md).
4. Nope. iohyve will stay `/bin/sh` until the end. The less dependencies the better. If I ever move to another higher level language, it will not be under the iohyve name, and will be a separate project. 

Even though I am closing this issue, feel free to respond, I will continue to answer you questions. :)

**Comment by till** [comment]
@pr1ntf Totally reasonable and thanks for the response!
1. Just for the record, it worked when I upgraded to the latest (tagged) release via ports.
2. Okay.
3. Okay, that makes sense, I was just wondering if writing some documentation (and I am happy to contribute that) would make sense to lay out steps so people don't just blindly execute commands and don't know what they just did.
4. Also fair! :) I was just reading through the shell script thinking, "there's got to be an easier way to parse `getopt`. ;)) But I totally understand what you mean in regards to dependencies. I couldn't figure out exactly if most tools on FreeBSD e.g. use Ruby or Python, whatever is "standard" or more likely to be installed. But I'll research that and see.

**Comment by pr1ntf** [comment]
Feel free to submit a PR about the documentation. I think we should keep what's in the man page, but if you'd like to edit the readme and add some more in depth info, I'd be more than happy to merge. 

I hear Ruby is all the rage, but it's not standard out of the box on FreeBSD. Nor is Python. Most stuff you see is C, C++, and Shell.
