### ISSUE TITLE
Handling use case when bridge0 is already there. 

### ISSUE THREAD

**Issue by allenmchan** [pr1ntf/iohyve#124]
I realize this is more of a question than an issue. 
I am running freenas 9.10 which is running freebsd 10.3 as a backend.

I have jails running that created a bridge0 already.
When using iohyve to install VMs, i get the error that bridge0 is already created.

I have been googling but cannot find how i should proceed.

The debian VM is created with iohyve but there is no networking. 

What i have tried: 
1. I manually added the tap0 as a member of bridge0
2. I have tried all variations of set net=[igb1|tap0|bridge0] and none would work
- My tests are pinging from the freenas host to the ip assigned to ubuntu VM and the other way around

Here is the ifconfig output

```
igb0: flags=8c02<BROADCAST,OACTIVE,SIMPLEX,MULTICAST> metric 0 mtu 1500
    options=403bb<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,JUMBO_MTU,VLAN_HWCSUM,TSO4,TSO6,VLAN_HWTSO>
    ether 00:25:90:4b:f9:c8
    nd6 options=9<PERFORMNUD,IFDISABLED>
    media: Ethernet autoselect (1000baseT <full-duplex>)
    status: active

igb1: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> metric 0 mtu 1500
    options=400b8<VLAN_MTU,VLAN_HWTAGGING,JUMBO_MTU,VLAN_HWCSUM,VLAN_HWTSO>
    ether 00:25:90:4b:f9:c9
    inet 192.168.0.106 netmask 0xffffff00 broadcast 192.168.0.255
    inet 192.168.0.186 netmask 0xffffff00 broadcast 192.168.0.255
    inet 192.168.0.187 netmask 0xffffff00 broadcast 192.168.0.255
    inet 192.168.0.188 netmask 0xffffff00 broadcast 192.168.0.255
    nd6 options=9<PERFORMNUD,IFDISABLED>
    media: Ethernet autoselect (1000baseT <full-duplex>)
    status: active

lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> metric 0 mtu 16384
    options=600003<RXCSUM,TXCSUM,RXCSUM_IPV6,TXCSUM_IPV6>
    inet6 ::1 prefixlen 128
    inet6 fe80::1%lo0 prefixlen 64 scopeid 0x3
    inet 127.0.0.1 netmask 0xff000000
    nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>

bridge0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
    ether 02:59:dc:8e:5f:00
    nd6 options=1<PERFORMNUD>
    id 00:00:00:00:00:00 priority 32768 hellotime 2 fwddelay 15
    maxage 20 holdcnt 6 proto rstp maxaddr 2000 timeout 1200
    root id 00:00:00:00:00:00 priority 32768 ifcost 0 port 0
    member: tap0 flags=143<LEARNING,DISCOVER,AUTOEDGE,AUTOPTP>
            ifmaxaddr 0 port 6 priority 128 path cost 55
    member: epair0a flags=143<LEARNING,DISCOVER,AUTOEDGE,AUTOPTP>
            ifmaxaddr 0 port 5 priority 128 path cost 2000
    member: igb1 flags=143<LEARNING,DISCOVER,AUTOEDGE,AUTOPTP>
            ifmaxaddr 0 port 2 priority 128 path cost 20000

epair0a: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> metric 0 mtu 1500
    options=8<VLAN_MTU>
    ether 02:ff:20:00:05:0a
    nd6 options=1<PERFORMNUD>
    media: Ethernet 10Gbase-T (10Gbase-T <full-duplex>)
    status: active

tap0: flags=8942<BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> metric 0 mtu 1500
    options=80000<LINKSTATE>
    ether 00:bd:ea:c8:f9:00
    nd6 options=9<PERFORMNUD,IFDISABLED>
    media: Ethernet autoselect
    status: active
    Opened by PID 12482
```

**Comment by EpiJunkie** [comment]
Could we get the output of `ifconfig -v` and `iohyve getall <insert-guest-name>`? I have a couple of guesses in mind but I am not sure without more data (preferable formatted as well). Thanks.

**Comment by EpiJunkie** [comment]
The reason I am asking for `ifconfig -v` output is that I believe the hardware offloaders are causing the issue. But it is difficult to tell with the output above only showing the code representation rather than the human friendly version of the flags that are enabled. The `-v` flag should provide the human friendly output.

I ran into a very similar situation recently. I could ping the jails to & from bhyve guests but I could not pass any actual traffic. From other physical devices I had no issue passing traffic. The problem ended up being the hardware offloaders (TSO, HWSUM, etc) were causing the issue, which I found kind of ironic considering the traffic was not making it to the hardware in my case. I used `tcpdump` and could see the traffic had checksum errors. I turn off the hardware offloaders and everything started working, took me two weeks to figure this out. In hindsight I should of ran `tcpdump` on the first day.

Try turning off the hardware offloading, then rerun `ifconfig -v` if it took effect, then test to see if you can pass actual traffic.

Disable hardware offloading:
`ifconfig igb0 -rxcsum -txcsum -rxcsum6 -txcsum6 -vlanmtu -vlanhwtag -vlanhwfilter -vlanhwtso -tso -tso4 -tso6 -lro -vlanhwtso -vlanhwcsum down`
`ifconfig igb1 -rxcsum -txcsum -rxcsum6 -txcsum6 -vlanmtu -vlanhwtag -vlanhwfilter -vlanhwtso -tso -tso4 -tso6 -lro -vlanhwtso -vlanhwcsum down`
`ifconfig igb0 up`
`ifconfig igb1 up`
The `down ups` are probably unnecessary but I have not tested this.

The jails should be attached to the interface closest to the hardware in this case of vlan interfaces or the actual hardware interface in this case.

**Comment by allenmchan** [comment]
This is the output of ifconfig -v

```
[root@freenas] ~# ifconfig -v
igb0: flags=8c02<BROADCAST,OACTIVE,SIMPLEX,MULTICAST> metric 0 mtu 1500
    options=403bb<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,JUMBO_MTU,VLAN_HWCSUM,TSO4,TSO6,VLAN_HWTSO>
    ether 00:25:90:4b:f9:c8
    nd6 options=9<PERFORMNUD,IFDISABLED>
    media: Ethernet autoselect (1000baseT <full-duplex>)
    status: active
igb1: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> metric 0 mtu 1500
    options=400b8<VLAN_MTU,VLAN_HWTAGGING,JUMBO_MTU,VLAN_HWCSUM,VLAN_HWTSO>
    ether 00:25:90:4b:f9:c9
    inet 192.168.0.106 netmask 0xffffff00 broadcast 192.168.0.255
    inet 192.168.0.186 netmask 0xffffff00 broadcast 192.168.0.255
    inet 192.168.0.187 netmask 0xffffff00 broadcast 192.168.0.255
    inet 192.168.0.188 netmask 0xffffff00 broadcast 192.168.0.255
    nd6 options=9<PERFORMNUD,IFDISABLED>
    media: Ethernet autoselect (1000baseT <full-duplex>)
    status: active
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> metric 0 mtu 16384
    options=600003<RXCSUM,TXCSUM,RXCSUM_IPV6,TXCSUM_IPV6>
    inet6 ::1 prefixlen 128
    inet6 fe80::1%lo0 prefixlen 64 scopeid 0x3
    inet 127.0.0.1 netmask 0xff000000
    nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
    groups: lo
bridge0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
    ether 02:59:dc:8e:5f:00
    nd6 options=1<PERFORMNUD>
    groups: bridge
    id 00:00:00:00:00:00 priority 32768 hellotime 2 fwddelay 15
    maxage 20 holdcnt 6 proto rstp maxaddr 2000 timeout 1200
    root id 00:00:00:00:00:00 priority 32768 ifcost 0 port 0
    member: tap0 flags=143<LEARNING,DISCOVER,AUTOEDGE,AUTOPTP>
            ifmaxaddr 0 port 6 priority 128 path cost 55
    member: epair0a flags=143<LEARNING,DISCOVER,AUTOEDGE,AUTOPTP>
            ifmaxaddr 0 port 5 priority 128 path cost 2000
    member: igb1 flags=143<LEARNING,DISCOVER,AUTOEDGE,AUTOPTP>
            ifmaxaddr 0 port 2 priority 128 path cost 20000
epair0a: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> metric 0 mtu 1500
    options=8<VLAN_MTU>
    ether 02:ff:20:00:05:0a
    nd6 options=1<PERFORMNUD>
    media: Ethernet 10Gbase-T (10Gbase-T <full-duplex>)
    status: active
    groups: epair
tap0: flags=8942<BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> metric 0 mtu 1500
    options=80000<LINKSTATE>
    ether 00:bd:ea:c8:f9:00
    nd6 options=9<PERFORMNUD,IFDISABLED>
    media: Ethernet autoselect
    status: active
    groups: tap
    Opened by PID 12482


[root@freenas] ~# iohyve getall ubuntuguest
Getting ubuntuguest props...
persist      1
tap          tap0
con          nmdm0
install      no
loader       grub-bhyve
boot         0
net          igb1
name         ubuntuguest
description  Mon_Apr__4_20:26:13_PDT_2016
os           debian
size         20G
autogrub     \n
ram          1024M
bargs        -A_-H_-P
cpu          2
```

**Comment by EpiJunkie** [comment]
Could you put the output in the correct formatting? The reason the text is not showing is it is in <> which is getting parsed incorrectly. To format the output, one line before the code use ```` (4x backticks), then one line after the output put another ```` (4x backticks). Backtick is the key above tab.

Also did you check to see if traffic was passing after disabling the hardware offload options on both NICs?

**Comment by pr1ntf** [comment]
How is that `bridge0` set up? If it's set in your `/etc/rc.conf` can we take a look at that? (sanitized to protect data leaks, of course)

I can see via your `ifconfig` output that `tap0` is added to `bridge0` so this is indeed a strange issue at first glance.

**Comment by EpiJunkie** [comment]
@allenmchan thanks for the formatted output. Also, could you fix the formatting of your original posts? It will be good to see the missing `flags` and `options` and also to see the changes occurring. Thank you.

One glaring issue I can see is the `tap0` interface is not up. `UP` should be in the `<>` brackets below.

```
tap0: flags=8942<BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> metric 0 mtu 1500
```

To fix temporarily run:

```
ifconfig tap0 up
```

The persistent fix for `tap0` being up on boot is to change the following tunables under `System > Tunables`. 
- See [here on how to input tunables on FreeNAS](http://doc.freenas.org/9.10/freenas_system.html#tunables).
- Copy and paste the exact text _within_ the "" but do not include the double quotes.
- Reboots are necessary for the changes to take effect.

```
Variable: "net.link.tap.up_on_open"
Value: "1"
Type: Sysctl
Comment: Brings all TAP interface up automatically.
Enabled: Checked
ifconfig_bridge81="up addm v081 span tap8199 addm tap81"

Variable: "ifconfig_bridge0"
Value: "up addm tap0 addm igb1 addm epair0a"
Type: rc.conf
Comment: Adds tap0, igb1, and epair0a to bridge0 interface
Enabled: Checked
```

The `addm epair0a` portion in the last tunable might not be necessary. `epair` devices are used by FreeNAS jails to tunnel from within the jail to the bridge but only when the `VIMAGE` and `NAT` options are enabled. Are these options enabled for this jail? If so, then the FreeNAS forums might be a better source of information on how to diagnose.

The other issue I can see ([which is speculative right now](https://github.com/pr1ntf/iohyve/issues/124#issuecomment-206103800)) is the hardware TSO is still on. The hardware TSO very likely needs to be turned off for both `igb0` and `igb1` due to the shared PCI root (which is indicated by the sequential MAC address).

[Hardware offloading](https://en.wikipedia.org/wiki/Large_segment_offload) (or what I keep calling TSO) is indicated by these flags for each interface above. I believe there are a few more but if it has `SUM`, `HW`, or `TSO`, then it is a hardware offloader.

```
RXCSUM,TXCSUM,VLAN_HWTAGGING,VLAN_HWCSUM,TSO4,TSO6,VLAN_HWTSO
```

The problem with TSO is, it can corrupt the checksums for the TCP packets. This causes most packets to be dropped, so most connections do not occur. Pings seem to pass but that is about it. This is the most common on `bce` devices (Broadcom) however it has been known to occur on Intel devices as well. It is almost guaranteed to be a problem on `bce` devices built into Dell hardware. This was first [brought to my attention when using pfSense](https://doc.pfsense.org/index.php/Tuning_and_Troubleshooting_Network_Cards) on a Dell R610 which has a quad port `bce` Broadcom NIC built in.

The persistent fix for disabling TSO on boot is this: 

```
Variable: "hw.igb.tso_enable"
Value: "0"
Type: Loader
Comment: Disables TSO on all devices using igb driver
Enabled: Checked

Variable: "net.inet.tcp.tso"
Value: "0"
Type: Loader
Comment: 
Enabled: Checked

Variable: "ifconfig_igb0"
Value: "-rxcsum -txcsum -rxcsum6 -txcsum6 -vlanmtu -vlanhwtag -vlanhwfilter -vlanhwtso -tso -tso4 -tso6 -lro -vlanhwtso -vlanhwcsum up"
Type: rc.conf
Comment: Further turns off hardware offloading on igb0 interface
Enabled: Checked

Variable: "ifconfig_igb1"
Value: "inet 192.168.0.106 netmask 255.255.255.0 -rxcsum -txcsum -rxcsum6 -txcsum6 -vlanmtu -vlanhwtag -vlanhwfilter -vlanhwtso -tso -tso4 -tso6 -lro -vlanhwtso -vlanhwcsum up"
Type: rc.conf
Comment: Further turns off hardware offloading on igb1 interface
Enabled: Checked
```

For the `igb1` interface you _do_ need to configure the IP of the host machine. The IPs for the jails should automatically attached depending on the way FreeNAS is written.

In summary, run `ifconfig tap0 up`, if that works great, then set the `net.link.tap.up_on_open` and `ifconfig_bridge0` tunables to fix the permanently/persistently. If it still does not work after bringing `tap0` up, then try the remaining four tunables. Then report back.

Before setting these tunables I recommend [making a backup of the config (Console option #11)](http://doc.freenas.org/9.10/freenas_quick.html?highlight=console).

@pr1ntf Long term, I think [adding to the FreeNAS documentation](https://github.com/freenas/freenas/blob/master/docs/userguide/freenas_jails.rst) will reduce the number of issues reported here. I will work on sending a PR to their docs this weekend.

The PR will roughly be:
- Add some words about the difference bhyve provides over jails.
- How to add basic tunables to include their equivalent in rc.conf for `iohyve_enable="YES"` and `iohyve_flags="kmod=1 net=em0"`
- Advanced section with the tunables mentioned above for fine tuning.

Any input is appreciated.

**Comment by pr1ntf** [comment]
I see here. Since the `brdige0` is already there, `iohyve` neglects to do **ANY** of the network setup, which includes the setting of the sysctl tunable [in question](https://github.com/pr1ntf/iohyve/blob/master/iohyve#L210).

**Comment by allenmchan** [comment]
a simple `ifconfig tap0 up` fixed the issue.
I think i jumped too quickly into understand the code and hacking at the interfaces. 
Totally forgot the most simple answer. 

I just deployed two VMs and they are working perfectly from networking perspective. 

```
[root@freenas] ~# iohyve list
Guest            VMM?  Running?  rcboot?  Description
zoneminder001    YES   YES       NO       Wed_Apr__6_23:15:42_PDT_2016
zoneminderdb001  YES   YES       NO       Wed_Apr__6_23:41:46_PDT_2016
```

**Comment by allenmchan** [comment]
Oops didn't mean to close this. i do believe it will help if the iohyve script handled existing bridge0 interface better.

**Comment by pr1ntf** [comment]
I'm going to keep this open as a reminder to add a sysctl check. 
Thanks for all your help!

**Comment by allenmchan** [comment]
Actually thank you two for your time.

I am trying to go through your code and understand why i had to manually add tapX to the bridge0

In theory the __prepare_guest function should have added the tapX to bridge0 interface.

**Comment by pr1ntf** [comment]
Sysctl check added in master branch. Please let me know if you are still needing to manually add tap devices to the bridge.
