### ISSUE TITLE
Document how to start machines automatically  

### ISSUE THREAD

**Issue by optilude** [pr1ntf/iohyve#140]
`iohyve list` shows an `rcboot` flag but it is not clear what this is. There isn't otherwise much help to understand how to automatically boot virtual machines when the system starts.

I'm also struggling to understand how I need to manage the tap0 network interface. Does it need to be added to the bridge on each boot? Does it need to be brought up manually before starting the virtual machine?

**Comment by pr1ntf** [comment]
`iohyve set guestname boot=1` will get the job done. I had no documentation for this because GRUB guests couldn't boot at startup until recently. In fact, there may be some bugs still that need to get out. 

RE: tap interfaces:
iohyve will take care of setting up tap interfaces for you. 
There's a section in the readme that will go over what to put in your `/etc/rc.conf`:

```
iohyve_enable="YES"
iohyve_flags="kmod=1 net=em0"
```

This will tell iohyve to attach the `bridge0` interface to the network adapter `em0` at boot time. 

Whenever you run `iohyve start guestname` or `iohyve install guestname` or `iohyve uefi guestname` iohyve will automatically add the tap interface to the bridge.
