### ISSUE TITLE
Custom ostypes doesn't support linux

### ISSUE THREAD

**Issue by jbergstroem** [pr1ntf/iohyve#146]
Looks like it unconditionally invokes `-r host` as an argument to `grub-bhyve`. Perhaps introduce `custom-linux`?

**Comment by jbergstroem** [comment]
With the current logic I could probably just call it whatever iohyve doesn't match os against, but it'd likely be better to handle the case, no?

**Comment by EpiJunkie** [comment]
The great thing about this project is you can change the code as you see fit. If you think your changes reach beyond your own use-case, then open a pull request and let project use it. You have opened quiet a few issues in a short period of time that share a common thread of being grub/linux based. It seems there is an underlying issue that needs to be addressed rather than open so many issues. However, the feedback is truly appreciated. Just my thought as another user and someone who has submitted PRs to this project.

That said, is there a series of steps you take to draw this conclusion?

**Comment by jbergstroem** [comment]
@EpiJunkie what you didn't see was me sending an email to @pr1ntf saying that I acknowledge filing a few "low hanging" issues that likely should have been PR's, but that I also was in a situation where I couldn't fix them at the moment. I also said that I will file them shortly.

I find it unfortunate being called out on it, especially with such a low latency from the filed issue. I will file PR's against my issues, but bear in mind that making issues visible also enables discussion -- your comment does nothing other than silence potentially other people wanting to bring issues to light and question wanting to help improve. Why would you assume that I wouldn't file a PR? Food for thought, but can we have that discussion elsewhere? It's pretty obvious that this attempts to raise a discussion with regards to how `os=custom` should work.

**Comment by EpiJunkie** [comment]
My apologize for any offense I have caused. Agreed, we should finish this personal portion of the discussion out of band. I will reached out to you via the email in your commit logs.

To add to the topic here. I am still having a difficult time understanding your use-case. I think the point of `os=custom` is to use custom `grub.cfg` and `device.map` files stored on the host. Is there a distro you are using where you want to reference files on the guest? Can we add support for it into iohyve? I did [add Gentoo support into the installer portion on my branch](https://github.com/EpiJunkie/iohyve/tree/enh.gentoo-guest), I am still installing it now so I have not written the non-install portion. It should be easy. I am guessing this might be the OS you are trying to use based on your repo-s.

**Comment by jbergstroem** [comment]
@EpiJunkie no problem. Replying to your question: I also added gentoo support by modifying the script, but I can see a use case for `custom` since there are a ton of linux distributions (and opinions). Catering for all of them, when they change boot params or whatever just seems tedious. Since custom existed I thought that would be a better alternative. Btw, in regards to your branch; is `-r host` correct to pass in the installer section? Shouldn't it pass `cd0` as root device?

**Comment by EpiJunkie** [comment]
Agreed, keeping a huge database of distros is tedious. Especially with the folder inconsistency between distros and even versions sometimes. Not sure how else to address this, improvements have recently been made but the 'database' block of code still exists. I think we all would be open to a solution.

In regards to my branch, referencing the host is correct because I want to be referencing the custom `grub.cfg` file created on line 668. It works in booting the system and was adapted from code written in 2014. The `grub.cfg` then references all the files from `cd0`. I attempted to run the installer without any changes or success. I also attempted to UEFI boot without success.

**Comment by jbergstroem** [comment]
Thanks for elaborating on `-r host`. I believe that explains #149 as well. With this said, I think avoiding `custom` will be the best bet for linux systems that falls outside of the supported ones.  I'll fix `-d` (#148) and after that it should be just fine. I guess it might be worth noting that paths to kernel/etc in `grub.cfg` using non-supported linux types should reference "(cd0)". It would at least have helped me.

**Comment by pr1ntf** [comment]
A quick reminder that the best way to start a conversation about code in iohyve is to open an issue, not email me or ping me on Twitter or IRC. If you have the time to put in a PR, great, if not, now worries, your comment will not fall on deaf ears. 

That being said, I'd like to thank both of you for your input to the project. It's greatly appreciated.

Also, thanks to @EpiJunkie for picking up the slack and replying to all the issues that pop up while I am sleeping. Although it's not necessary, it does help get the conversation started and the ball rolling. 

:octopus:
