### ISSUE TITLE
Syntax differs from zfs

### ISSUE THREAD

**Issue by jbergstroem** [pr1ntf/iohyve#147]
When working with `iohyve` I now and then use zfs syntax instead of `iohyve`. Perhaps it would make sense to change it from `iohyve set <vm> foo=bar` to zfs's `zfs set foo=bar <vm>`?

**Comment by EpiJunkie** [comment]
Ultimately this one is up to @pr1ntf.

Currently PR #144 is open to make the formatting syntax to match ZFS's styling.

Part of the reason for the current syntax is that you can specify multiple arguments at once. For example:`iohyve set bguest cpu=1 ram=256 tap=tap2`.

**Comment by moogle19** [comment]
The multiple arguments are also available in the `zfs get` command.
I am also pro zfs style with the guest-name at the end of the command and would like to implement it, but I am currently waiting for feedback from @pr1ntf , if my PR #142 will get accepted before adding more stuff.

**Comment by moogle19** [comment]
One problem with this change is, that it may break some peoples scripts, workflows, etc..

**Comment by jbergstroem** [comment]
It might not be mine or your – @EpiJunkie – decision to make, but having our feedback when deciding will hopefully help. 

@moogle19 yes, it's unfortunate, but I think its still the right thing to do. The earlier the better so less people are impacted by it since I can only assume `iohyve` will grow in usage seeing how effective it is.

**Comment by pr1ntf** [comment]
This has been a complaint since the very beginning. Unfortunately, I won't be changing the syntax that drastically right now. Big changes are coming soon to the setting and getting of guest properties with the addition of a `.defaults` file. When that is pushed, I'll take a look at fixing the syntax, since there will be a major `UPDATING` file for that updating anyway. 

I'm adding this to the [roadmap](https://github.com/pr1ntf/iohyve/wiki/General-Path-to-1.0#077-goals) as a reminder. 

Thanks for your input!!
