### ISSUE TITLE
vswitch instead of bridge

### ISSUE THREAD

**Issue by network-shark** [pr1ntf/iohyve#189]
Hey, 
I'm using freebsd with vimage as a kernel extension. With that feature enabled all my Jails and my primary network interface are attached to vswitch1 and not to bridge0 . 

So now my virtual machine does not have ip connectivity anymore, because the tap interface is always attach to bridge0. I could not figure out how to configure iohyve to use vswitch1 as a default ? Any chance to change it ?

**Comment by pr1ntf** [comment]
As it stands right now, `iohyve` only attaches `tap` interfaces to `bridge0`. I am currently working on adding support for [more than one bridge interface](https://github.com/pr1ntf/iohyve/wiki/General-Path-to-1.0#079-goals) in `iohyve`.

I would definitely not be opposed to letting that be a `bridge` or a `vswitch`. 
Can you go through what you did to set up the `vswitch`? I would be interested in dropping proposed `VALE` support for `VIMAGE` if it's stable enough. 

This way users could use either `bridge` or `vswitch` interfaces, or even both if they wanted.

**Comment by EpiJunkie** [comment]
@sharky1337 as a temporary solution you can change [line 495](https://github.com/pr1ntf/iohyve/blob/master/lib/ioh-guest#L495) of `/usr/local/lib/iohyve/ioh-guest` from `ifconfig bridge0 addm $tap` to `ifconfig vswitch1 addm $tap`. After that either restart the host or manually add the `tap` interfaces to `vswitch1` with `ifconfig vswitch1 addm tap{n}`, where {n} is the tap interface number. 

@pr1ntf I believe "vswitch1" is an arbitrary name for a bridge device. A bridge name can be changed by using this command `ifconfig bridge0 name vswitch0` or even `ifconfig bridge0 name TacoBell`. The name seems to be truly arbitrary but is limited to a 15 character length. You can change the name of any interface with `ifconfig` with this same syntax.

I do not believe integrating `VIMAGE` into iohyve is possible because it is not implemented in bhyve. At least with the method of utilizing `VIMAGE` through an `epair` device. While I have not used VIMAGE in a jail myself, I did take a look at the code in `iocage` and I think I roughly figured it out. [It seems that](https://github.com/iocage/iocage/blob/a2d9c47eef7c767fe704a3846e2e9f8bf45e0c03/lib/ioc-network#L71) an `epair` pair interface is created, then the 'a' portion gets attached to host and the 'b' side gets attached in the jail. Both are renamed. It then seems that both are associated to a jail ID and use a '`vnet`' directive in the `ifconfig` command: "`ifconfig $epair_b vnet ioc-${2}`". The last part being where the magic happens.

**Comment by pr1ntf** [comment]
Yes, `epair` is still where the magic happens, I had assumed something had changed in the latest updates where you can add `tap` interfaces, thus the question to the user still remains:

> Can you go through what you did to set up the vswitch? 

If it's just a normal TacoBell bridge, not it's own network stack, then `VALE` will still be the way to go.

**Comment by pr1ntf** [comment]
If there are no more questions or comments on this, I'll close out the issue. Having support for having more than just `bridge0` is planned, and should be available soon, pending bringing in patches from #170 and #183.

**Comment by network-shark** [comment]
Hello pr1ntf , 

sorry for the late reply, I was on pto. 

I used this tutorial for compiling the kernel. 

https://jsherz.com/freebsd/jails/kernel/vnet/2015/11/17/custom-kernel-jails-vnet.html

This is how my vswitch looks like.

vswitch1: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
        ether 02:fe:4a:c8:9c:01
        nd6 options=1<PERFORMNUD>
        id 00:00:00:00:00:00 priority 32768 hellotime 2 fwddelay 15
        maxage 20 holdcnt 6 proto rstp maxaddr 2000 timeout 1200
        root id 00:00:00:00:00:00 priority 32768 ifcost 0 port 0
        member: epair4a flags=143<LEARNING,DISCOVER,AUTOEDGE,AUTOPTP>
                ifmaxaddr 0 port 10 priority 128 path cost 2000
......
        member: igb0 flags=143<LEARNING,DISCOVER,AUTOEDGE,AUTOPTP>
                ifmaxaddr 0 port 1 priority 128 path cost 2000000

For settings up a  jail I'm using ezjail .

This is my example configuration.

export jail_samba_hostname="samba"
export jail_samba_rootdir="/usr/jails/samba"
export jail_samba_exec_start="/bin/sh /etc/rc"
export jail_samba_exec_prestart0="ifconfig epair4 create up"
export jail_samba_exec_prestart1="ifconfig vswitch1 addm epair4a"
export jail_samba_exec_poststart0="ifconfig epair4b vnet samba"
export jail_samba_exec_poststart1="jexec samba /sbin/dhclient epair4b "
export jail_samba_exec_poststart2="jexec samba /sbin/ifconfig epair4b inet6 <<IPV6ADDRESS>> prefixlen 64"
export jail_samba_mount_enable="YES"
export jail_samba_devfs_enable="YES"
export jail_samba_devfs_ruleset="devfsrules_jail"
export jail_samba_procfs_enable="YES"
export jail_samba_fdescfs_enable="YES"
export jail_samba_image=""
export jail_samba_imagetype="zfs"
export jail_samba_attachparams=""
export jail_samba_attachblocking=""
export jail_samba_forceblocking=""
export jail_samba_zfs_datasets=""
export jail_samba_cpuset=""
export jail_samba_fib=""
export jail_samba_parentzfs="zroot/ezjail"
export jail_samba_parameters="enforce_statfs=1 allow.mount=1 allow.mount.zfs=1 allow.mount.procfs=1 allow.mount.devfs=1 allow.raw_sockets=1 allow.sysvipc=1"
export jail_samba_post_start_script=""
export jail_samba_retention_policy=""
export jail_samba_exec_poststop0="ifconfig epair4a destroy"

I have to use a static ipv6 address, because I could not get ipv6 dhcp working. IPv4 dhcp works well.

**Comment by pr1ntf** [comment]
Thanks for the info!
