### ISSUE TITLE
Adding serveral bridge interface

### ISSUE THREAD

**Issue by stefb69** [pr1ntf/iohyve#221]
Hello,

Is it possible to have serveral bridged interfaces ? (one the the main ethernet and the other to a vlan ?)
I'm thinking about running pfsense with iohyve

Regards,
Stéphane

**Comment by pr1ntf** [comment]
It is not currently possible to have multiple bridges in `iohyve` without a bit of work. Right now, everything is hard coded to `bridge0` in `'iohyve`.  It is planned, but because everytime I go in to add the feature, I end up re-writing a bunch of other stuff that should be re-written and then stuff breaks all over the place. 

It should land eventually. 

I have heard of `iohyve` users using pfSense in the past, but with passing through the NIC's. 

In theory, you don't need to have `iohyve` set up your tap and bridge interfaces. You can use the `iohyve set` function to attach your own devices as outlined in the [man page](https://github.com/pr1ntf/iohyve/blob/master/iohyve.8.txt#L202) (look for the `pcidev:[n]=<spec>` line. This has not been tested by me at all, so be aware. Remember if you don't use `iohyve` to set up your networking, you will have to "roll your own" `rc.conf` and turn off `iohyve` tap devices with something like `iohyve set guestname tap=-`.
