### ISSUE TITLE
How can we apply pf rules for a guest?

### ISSUE THREAD

**Issue by TheoLA** [pr1ntf/iohyve#234]
Hi, I would like to have an IP whitelist (outgoing traffic) for some of my guests but couldn't figure out how to apply rules for them. How can we do that?

**Comment by pr1ntf** [comment]
That's a pretty broad question, so I'm going to give a very broad answer. 

I personally have used `pf` with `iohyve` in the past. I wrote something quick about it [here](https://github.com/pr1ntf/iohyve/wiki/Using-iohyve-over-WiFi), but that may not be what you are looking for. What you need to know about `iohyve` and it's auto configuration of the network is that it attaches a bridge (Only `bridge0` for now), to a network interface on your host (something like `em0` or `igb0`). `iohyve` then gives each guest at tap device (`tapN`) and attaches that to `bridge0`. 

Here is a poorly designed text diagram of this:
```
   ----------              --------           \MMMMMMMMM/
  | bridge0 | <---------> | igb0 | <------> < INTERNETS >
  ----------              --------           /WWWWWWWWW\
    ___|________
   |           |
 ------      ------
| tap0 |    | tap6 |
 ------      ------

```

In the wiki [article](https://github.com/pr1ntf/iohyve/wiki/Using-iohyve-over-WiFi) I linked, I used `pf` to forward everything from `wlan0` to my guests behind a NAT. The guests can reach the outside internet. Traffic coming from outside will be blocked, even on the host. If I run my SSH server on the host at port `4444` then I would need to add something like `pass in quick on $if proto tcp from any to $pub port 4444`. Otherwise it would appear as closed from the outside. 

Of course, like I said earlier, you are looking to whitelist your outgoing traffic from the guests. You may not need a NAT. Everyone's `pf` setup is going to be different. [The Book of pf](https://www.nostarch.com/pf3) by Peter N. M. Hansteen is a wonderful resource when dealing with `pf`.

**Comment by TheoLA** [comment]
Thank you for clearing things up. Let's say we would like to allow guest-a (tap0) to connect to guest-b (tap1) on port 1234 only and drop everything else. That would be impossible with this setup or am I missing something?

**Comment by pr1ntf** [comment]
There are probably a half a dozen ways to accomplish this. I am not a `pf` expert. I literally just read a book once. 🤓 

As stated previously:

>I wrote something quick about it here, but that may not be what you are looking for.

> Of course, like I said earlier, you are looking to whitelist your outgoing traffic from the guests. You may not need a NAT. 

I'm just trying to show you how `iohyve` sets up it's networking to better help you in case you wanted to try this with `iohyve`.

There are also other `bhyve` managers/wrappers that give you better control of network separation. I know `vm-bhyve` uses `dnsmasq` to do some separation. I'm not sure if `chyves` (a fork of `iohyve`) has support for it yet, but they were going to implement `VALE` switches with `NETMAP`. We have specifically chosen not to do this in `iohyve` so we don't have to troubleshoot everyone's `/etc/pf.conf` or network in general, as that would cause too many headaches. Users can still attempt things, but we will not support it. 

Seriously though, check out the book, it's wonderful.
