### ISSUE TITLE
UEFI Changes

### ISSUE THREAD

**Issue by pr1ntf** [pr1ntf/iohyve#241]
UEFI Guests created before UEFI refactor will not boot. If a ZFS property (like an `iohyve` property) is not set, it is returned with a value of `-`, not an empty string. Also, instead of failing, if no sectorsize property is present, we should simply not set one. (This feature is only needed by some older Windows versions).

**Comment by murf0** [comment]
Thanks for merging!
Bug on my part, Fixed the compare for "-" instead of empty string.
If  sectorsize is not set as a zfs property the Sectorsize is left unset and a warning is shown. (Since this breaks old guests) UEFI boot continues without any sector set.
I also added some more code comment to clarify the issue, and added at reference to this ticket.

https://github.com/pr1ntf/iohyve/pull/242

**Comment by pr1ntf** [comment]
Thanks!
