### ISSUE TITLE
nas4free compatibility

### ISSUE THREAD

**Issue by christophkreutzer** [pr1ntf/iohyve#243]
There are some points I needed to fix to get iohyve working on nas4free. I would be happy if we could fix them :)

To check if a user is root the following would also be possible:
`[ "$(id -u)" != "0" ]` instead of the usage of `whoami`, which is missing in nas4free

While running `iohyve setup`
> grep: /var/log/dmesg: No such file or directory

I've seen it also checks `/var/run/dmesg.boot`, but I still get the warning message, also when VT-x UG is supported:
```
nas iohyve/ root~$ grep 'VT-x:' /var/run/dmesg.boot | grep 'UG'
  VT-x: PAT,HLT,MTF,PAUSE,EPT,UG,VPID
```

**Comment by pr1ntf** [comment]
Right on! Thanks for the heads up! 

Good point on the root user check, I'll see what we can do to fix it. 

The `dmesg` issues are all over the place right now. I want to re-do that part of the `iohyve setup` function. Different FreeBSD variants have different `dmesg` log locations, and different outputs with verbosity tuning. 

The `iohyve setup` function should have finished if everything was run correctly. Because of these issues, it's only a warning, not something that kills the function.

**Comment by christophkreutzer** [comment]
Yes, right, it was working correctly, just gave these warnings. Thanks for the feedback.

I'm currently working on setting it up on a nas4free box. There are some obstacles because the root fs is a ram disk and some tools are missing (like `make`). However, they have all bhyve binaries bundled 👍 

If I have a good solution I'll contribute it for the wiki.

**Comment by pr1ntf** [comment]
That would be rad! 😎

**Comment by pr1ntf** [comment]
We have added `[ "$(id -u)" != "0" ]` as the root check. We are still in the process of changing over the dmesg stuff. Thanks for the help!
