### ISSUE TITLE
check for networking setup?

### ISSUE THREAD

**Issue by internationils** [pr1ntf/iohyve#246]
I had networking issues on the guest and could not connect to anything. I could not find anything wrong, and tried to set up the networking again, and then it worked.
Problem is, I could find no indication in the getall and other setup list commands of anything wrong.
Please either add a check or some way to see if / how 'net' is set.
The solution is mentioned in https://github.com/pr1ntf/iohyve preflight checklist, but a way to figure out that that is the problem would be helpful.
```
[root@freenas /iohyve]# iohyve setup net=igb0
bridge0 is already enabled on this machine...
Setting up correct sysctl value...
net.link.tap.up_on_open: 0 -> 1
[root@freenas /iohyve]# iohyve setup net=igb0
bridge0 is already enabled on this machine...
sysctl already setup properly as well...
```

**Comment by pr1ntf** [comment]
I don't understand the question? I understand that you were having network issues but you resolved them?

**Comment by internationils** [comment]
I'm saying I want to use a iohyve status command or something to see if what the value of 'net' is set to. I didn't realize I had forgotten to iohyve_enable="YES" and iohyve_flags="kmod=1 net=em0" so the networking was not set up. At present I see no way to figure this out or check this except for guessing.

**Comment by pr1ntf** [comment]
A check of `ifconfig` on the host gives a rundown of all the network interfaces on the host.

**Comment by internationils** [comment]
Ah OK. The tap0 probably didn't exist when I booted the guest the first time. OK, then would it be possible to change
```
$ sudo iohyve getall www-bhyve
Getting www-bhyve iohyve properties...
...
tap            tap0
...
```
...to say something like `tap   tap0 (inactive)` or something similar if the interface isn't set up as needed? Then that points directly to the problem and saves debugging time.

**Comment by pr1ntf** [comment]
The interface `tap0` is created when the guest is started. Your problem was that your `bridge0` interface was not setup properly, or the correct sysctl's were not in place. There are many ways to setup networking, so it's hard to say "your setup is wrong, try xyz..." (Not everyone uses `iohyve setup` to set networking.) We are going to have to assume that the user has followed instructions and properly setup the networking. I think this is better solved in documentation, rather than adding logic to the actual scripting.

**Comment by internationils** [comment]
Hm, but I have tap0 set as the tap, shouldn't there be an error when booting that points to tap0 not being created since something is wrong? 
If that's not doable / sensible, feel free to close the issue as is, but it would be nice to have some hint of what's wrong. I was playing with the interfaces in the guest, dhclient, and routing in the guest to try and solve it before I looked at the host and tried `iohyve setup net=igb0` again. 
Thanks for your help!

**Comment by pr1ntf** [comment]
Again, it's hard to warn for things like this since there are so many different ways to set up networking besides the default `iohyve` way. In the future, you can debug the networking by simply checking `ifconfig` and making sure that your interface (`igb0`) and your tap interfaces (ex: `tap0`) are members of the bridge (usually `bridge0`). 

Thanks for the insight though!
