### ISSUE TITLE
Multiple Datastore different pool and datastore on NFS

### ISSUE THREAD

**Issue by Firemad03** [pr1ntf/iohyve#258]
Hi,

First congratulation with the iohyve :) really it's a lot easier vs bhyve. 

I got some questions and sorry if it's answered somewhere but I didn't find it in the wiki.

1) Does iohyve support multiple datastore from different pool ?

Let's say that I create a VM on a pool that I called Tank and I want to create a VM on a second pool that I called Tank2. Does iohyve support that ?

The main reason behind this is because I want to create a VM on a SSD pool and another VM on another pool that is slower (HDD for example)

2) Does iohyve support a VM that have a pool on another server with NFS ? 

I want to run a VM on my server but host it on the network with NFS that got a different zfs pool

I know that the iohyve setup do that for the configuration of iohyve and I can setup it on a pool and I'm fine with that but I'm talking only to host the vm data to another pool locally or remotely.

Thanks

**Comment by pr1ntf** [comment]
> Does iohyve support multiple datastore from different pool ?

We have supported this for quite some time now. There have been bugs alongs the way, with the most recent ones having to do with disks beings stored across two different pools. (like disk0 being on tankA and disk1 being on tankB) To fix this, we just removed support for that. You can still store vm's across multiple pools (vm0 on tankA, vm1 on tankB).

You can refer to the [man page](https://github.com/pr1ntf/iohyve/blob/master/iohyve.8.txt#L65) for more info on setting up pools. 

> Does iohyve support a VM that have a pool on another server with NFS ?

Nope. Probably won't. Since the very beginning, we've wanted everything in ZFS and ZFS user properties. That's just not what I set out to build. The NFS idea brings a whole other layer to things, where you need a data store (preferably fast) since ZFS gave you that with the zpool. I'm just not interested in making that killer app that has to talk to some database and then refactor all the iohyve code that deals with zfs user properties.

**Comment by Firemad03** [comment]
Great, thx for the long answer :) I understand the NFS reasons behind that.

I will look to the man page.
