### ISSUE TITLE
iohyve list - show ip address of the vm

### ISSUE THREAD

**Issue by Firemad03** [pr1ntf/iohyve#282]
Hi,

Small idea: add the ip address of the vm in another column when we show all vms with iohyve list

![image](https://user-images.githubusercontent.com/24792889/28185833-e0238cb0-67e6-11e7-9671-dbbb4b660ee8.png)

The reason behind this is because I always forget the ip address when I want to do a vnc and it will be easier.

Thanks

**Comment by pr1ntf** [comment]
I usually add IP info to the guest's `description` property. That way, they show up in the output of `iohyve list`. 

You should be able to set any string as the description as described in the [man page](https://github.com/pr1ntf/iohyve/blob/master/iohyve.8.txt#L399) as long as you put the string between two "double quotes" (`"`) and the string does not contain any "double quotes" (`"`) (Everything after the second `"` will be ignored).

In order to limit the amount of default properties a guest has, we try not to create new properties that have no bearing on the iohyve controlled settings. If there was an easy way for iohyve to set or determine a guest's IP, we would add it, but at this time, there is no simple or easy way to do so, without some kind of 3rd party configuration management. 

I'm going to close this issue out, but if you have further questions on this topic, feel free to reply, and I can reopen it. If you have trouble setting a `description` string, please open a separate ticket. 

Thanks!

**Comment by Firemad03** [comment]
Great I understand.

What is the maximum size for the description field ? Can I put a very long description or we have a limit ? 

I read the man but it doesn't specify anything about that.

**Comment by pr1ntf** [comment]
The ZFS documentation states "The maximum length of the user property value is 1024 characters."

http://docs.oracle.com/cd/E19253-01/819-5461/gdrcw/index.html

**Comment by Firemad03** [comment]
Ah perfect! I suggest maybe to add it in the man of iohyve in the description of the description option. I wouldn't have the reflex to check the zfs doc ;)
