### ISSUE TITLE
Debian 8.2 LVM Does Not Start

### ISSUE THREAD

**Issue by ghost** [pr1ntf/iohyve#63]
I installed Debian 8.2 using the instructions:

```
iohyve set debguest loader=grub-bhyve
iohyve set debguest os=debian
iohyve install debguest debian-8.2.0-amd64-i386-netinst.iso
iohyve console debguest
```

When I try to start the guest with 'iohyve stary debguest' I get an unusable prompt. I see my regular prompt and below that it says "grub>"
Anything that I type does not get echoed and I am unable to get the guest to boot.

**Comment by pr1ntf** [comment]
Did you select to install Debian on LVM by chance?

**Comment by ghost** [comment]
Yeah, that's exactly what I did.

**Comment by ghost** [comment]
Oh no, I just remembered that there was some bug that I was running into when using bhyve with a debian guest using LVM.

**Comment by pr1ntf** [comment]
Well, it works, it's just hacky in iohyve at the moment. 
This is changing soon thanks to some help from Peter of `grub2-bhyve`.
Bear with me? 

First off, kill off any process with the name `debguest`

```
pgrep -f debguest
XXXXX
XXXXY
XXXXZ
```

Kill those how you wish. Then destroy the guest in vmm: `iohyve destroy debguest`

Run `iohyve conreset` just to be sure if you want. 

Next set the os property back to default: `iohyve set debguest os=default`

Start the guest: `iohyve start debguest`

You should have access to the grub menu now. 

If you run `ls (hd0,msdos1)/grub/` you can see the `grub.cfg` is in there. 
That's why I am changing how `iohyve` utilizes `grub2-bhyve` specifically how it uses the `-g` option. Hint: look how it uses device maps. I will still utilize the `os` property along with the `autogrub` property. 

For now, there is technically a way you can boot, utilizing some hacky things I mention in the CentOS 6 how to in the readme.

**Comment by manasb** [comment]
I see, thanks.

I had a separate question but didn't know how to ask you, hope it's okay to ask you here.

I have a .img file that is associated with a bhyve guest which was run in the traditional way (grub-bhyve and bhyve), how can I add in that .img file to a guest running through iohyve?

**Comment by pr1ntf** [comment]
Please open a new issue, as I may have a solution for this if the img was installed using `ahci-hd` and not `virtio-blk`.

**Comment by pr1ntf** [comment]
This has been fixed. 

If you run `iohyve set debian8 os=d8lvm` the autogrub will boot just fine.
