### ISSUE TITLE
Systematically recognise the location of the ramdisk kernel for OpenBSD

### ISSUE THREAD

**Issue by sevan** [pr1ntf/iohyve#88]
At the moment the path for the bsd.rd kernel results in hardcoding the version of OpenBSD (at present 5.7 or 5.8 (broken if you want to boot -current (5.9))). It would be better if the system worked out where the kernel is so as to save having to maintain version numbers.

**Comment by jungle-boogie** [comment]
I observed this last week with the 5.9 beta snapshots:
http://ftp.openbsd.org/pub/OpenBSD/snapshots/amd64/

**Comment by pr1ntf** [comment]
The hard coding has turned out to be a pain, yes. I've had some discussion on this on Twitter over a recent break. I took that conversation and thought on it a lot. I guess a deeper question is: `What operating systems are supported by iohyve?`

What I came up with was this:
A major change to how grub-loaded guests is coming. This will involve including custom `grub.cfg` files that are stored in a `Template` dataset much like `ISO`'s and `Firmware`'s. 

What I've been wondering is: _What ~~operating systems~~ _templates_ are supported by iohyve?_

Of course, this means I've got to understand release cycles of the operating systems I would like to support. 

Here is a Wiki article outlining this idea: https://github.com/pr1ntf/iohyve/wiki/Guest-Operating-System-Support

Thoughts, questions, comments?

**Comment by jungle-boogie** [comment]
thanks for your efforts on this thus far, @pr1ntf! 

I've added some text to the page for openbsd. Basically there's `-release` and a snapshot of `-current`. 
Technically there's also -stable but that's not made into an ISO image.

Another important thing to know is that openbsd supports the current release and one version back for patches. So 5.8 is the current release and 5.7 is still patched:
http://www.openbsd.org/errata58.html

**Comment by sevan** [comment]
I'm not sure I agree with having to learn the release cycles of operating systems you want to support. The file name remains the same, an element in the path changes. How can you avoid relying on the specifying the element that changes regularly?

**Comment by pr1ntf** [comment]
@jungle-boogie: Thanks! 

@sevan: You're talking about automating the process? Like once `iohyve set obsd57 os=obsd` the autogrub (piping to grub) see's `obsd` then manually looks in the filesystem for where the kernel bits are?

**Comment by pr1ntf** [comment]
I don't think we will be implementing this right now. There would be a lot of work that would need to be done in `grub-cli`. Perhaps at a later date once iohyve's use of `grub-bhyve` improves. 

If it gets brought back up by someone else, I'll point them here. 

Thanks for your help, you two!
